# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
# SPDX-FileCopyrightText: Open Energy Transition gGmbH
#
# SPDX-License-Identifier: MIT

tennet_capacity:
  NL01AC-NL02AC: 1.0
  NL01AC-NL03AC: 5.4
  NL02AC-NL04AC: 4.5
  NL02AC-NL05AC: 2.6
  NL03AC-NL04AC: 3.7
  NL04AC-NL08AC: 2.0
  NL05AC-NL07AC: 2.6
  NL06AC-NL07AC: 2.2
  NL06AC-NL09AC: 2.0
  NL07AC-NL11AC: 2.0
  NL08AC-NL12AC: 2.0
  NL09AC-NL10AC: 2.6
  NL09AC-NL11AC: 3.5
  NL10AC-NL11AC: 2.6
  NL11AC-NL13AC: 3.1
  NL12AC-NL16AC: 1.6
  NL13AC-NL15AC: 2.2 # TODO: Temporary Skip
  # NL13AC-NL14AC: 2.2
  NL13AC-NL16AC: 3.6
  # NL14AC-NL15AC: 2.2



offshore_buses: true

res_tyndp_mapping:
  offwind-ac-fb-r: offwind-ac
  hydro-ror: ror
  onwind: onwind
  solar-pv-utility: solar
  solar-pv-rooftop: solar rooftop
  # dsr: False
  offwind-dc-fb-r: offwind-dc
  # offwind-h2-fb-oh: false
  # offwind-dc-fb-oh: offwind-dc

conv_tyndp_mapping:
  nuclear: nuclear
  gas-conv-old1: OCGT
  gas-conv-old2: OCGT
  gas-ccgt-old1: CCGT
  gas-ccgt-old2: CCGT
  gas-ccgt-new: CCGT
  gas-ccgt-ccs: CCGT
  gas-ccgt-present1: CCGT
  gas-ccgt-present2: CCGT
  gas-ocgt-old: OCGT
  gas-ocgt-new: OCGT
  coal-old1: coal
  coal-old2: coal
  coal-new: coal
  coal-ccs: coal
  lignite-old1: lignite
  lignite-old2: lignite
  lignite-new: lignite
  lignite-ccs: lignite
  oil-light: oil
  oil-heavy-old1: oil
  oil-heavy-old2: oil
  oil-shale-old: oil
  oil-shale-new: oil
  h2-ccgt: CCGT

store_tyndp_mapping:
  battery: battery
  H2 cavern-storage: H2 Store
