# SPDX-FileCopyrightText: Contributors to Open-TYNDP <https://github.com/open-energy-transition/open-tyndp>
#
# SPDX-License-Identifier: CC0-1.0

benchmarking:
  enable: false
  remove_last_day: false
  spatial:
    by_bus: true
    by_country: true


  tables:
    final_energy_demand:
      table_type: scenario_comparison
      rfc_sources:
      - report
      unit: TWh
      report:
        sheet_name: 5-
        index_col: 2
        header: [4, 5]
        names:
          index:
          - carrier
          column:
          - scenario
          - year
      mapping:
        AC: electricity
        AC_OH: electricity
        low voltage: electricity
        H2: hydrogen
        exogenous gas demand: methane
        oil: liquids
        kerosene for aviation: liquids
        shipping oil: liquids
        land transport oil: liquids
        coal: solids
        solid biomass: biofuels

    elec_demand:
      table_type: scenario_comparison
      rfc_sources:
      - report
      - vp
      unit: TWh
      report:
        sheet_name: 23-
        index_col: [2, 3]
        header: 4
        names:
          index:
          - scenario
          - year
          column:
          - carrier
      mapping:
        electricity: final demand (inc. t&d losses, excl. pump storage )

    methane_demand:
      table_type: scenario_comparison
      rfc_sources:
      - report
      unit: TWh
      report:
        sheet_name: 8-
        index_col: 2
        header: [4, 5]
        nrows: 15
        names:
          index:
          - carrier
          column:
          - scenario
          - year
      mapping:
        CCGT: power generation
        OCGT: power generation
        gas-ccgt: power generation
        gas-ccgt-old1: power generation
        gas-ccgt-old2: power generation
        gas-ccgt-new: power generation
        gas-ccgt-present1: power generation
        gas-ccgt-present2: power generation
        gas-ccgt-ccs: power generation
        gas-ocgt: power generation
        gas-ocgt-old: power generation
        gas-ocgt-new: power generation
        gas-conv: power generation
        gas-conv-old1: power generation
        gas-conv-old2: power generation
        other-non-res-gas-conv: power generation
        other-non-res-gas-conv-old1: power generation
        other-non-res-gas-conv-old2: power generation
        other-non-res-gas-ccgt: power generation
        other-non-res-gas-ccgt-old1: power generation
        other-non-res-gas-ccgt-old2: power generation
        other-non-res-gas-ccgt-new: power generation
        other-non-res-gas-ccgt-present1: power generation
        other-non-res-gas-ccgt-present2: power generation
        other-non-res-gas-ccgt-ccs: power generation
        other-non-res-gas-ocgt: power generation
        other-non-res-gas-ocgt-old: power generation
        other-non-res-gas-ocgt-new: power generation
        SMR: smr
        SMR CC: smr
        exogenous gas demand: exogenous demand

    hydrogen_demand:
      table_type: scenario_comparison
      rfc_sources:
      - market_out
      - report
      unit: TWh
      report:
        sheet_name: 10-
        index_col: 2
        header: [4, 5]
        nrows: 15
        names:
          index:
          - carrier
          column:
          - scenario
          - year
      mapping:
        H2 turbine: power generation
        h2-ccgt: power generation
        h2-fuel-cell: power generation
        Fischer-Tropsch: e-fuels
        Sabatier: e-fuels
        methanolisation: e-fuels
        H2 exogenous demand: exogenous demand

    power_capacity:
      table_type: scenario_comparison
      rfc_sources:
      - market_out
      - report
      - vp
      unit: GW
      report:
        sheet_name: 25-
        index_col: [2, 3]
        header: 4
        nrows: 10
        ncolumns: 17
        names:
          index:
          - scenario
          - year
          column:
          - carrier
      mapping:
        offwind-dc-fl-r: wind offshore
        offwind-dc-fl-oh: wind offshore
        offwind-dc-fb-r: wind offshore
        offwind-dc-fb-oh: wind offshore
        offwind-ac-fl-r: wind offshore
        offwind-ac-fb-r: wind offshore
        offwind-h2-fb-oh: wind offshore
        offwind-h2-fl-oh: wind offshore
        onwind: wind onshore
        solar-pv-rooftop: solar
        solar-pv-utility: solar
        h2-ccgt: hydrogen
        h2-fuel-cell: hydrogen
        coal: coal + other fossil (incl. biofuels)
        coal-old1: coal + other fossil (incl. biofuels)
        coal-old2: coal + other fossil (incl. biofuels)
        coal-new: coal + other fossil (incl. biofuels)
        coal+ccs: coal + other fossil (incl. biofuels)
        lignite: coal + other fossil (incl. biofuels)
        lignite-old1: coal + other fossil (incl. biofuels)
        lignite-old2: coal + other fossil (incl. biofuels)
        lignite-new: coal + other fossil (incl. biofuels)
        lignite+ccs: coal + other fossil (incl. biofuels)
        oil-heavy: oil (incl. biofuels)
        oil-heavy-old1: oil (incl. biofuels)
        oil-heavy-old2: oil (incl. biofuels)
        oil-light: oil (incl. biofuels)
        oil-shale: oil (incl. biofuels)
        oil-shale-old: oil (incl. biofuels)
        oil-shale-new: oil (incl. biofuels)
        gas-ccgt: methane (incl. biofuels)
        gas-ccgt-old1: methane (incl. biofuels)
        gas-ccgt-old2: methane (incl. biofuels)
        gas-ccgt-new: methane (incl. biofuels)
        gas-ccgt-present1: methane (incl. biofuels)
        gas-ccgt-present2: methane (incl. biofuels)
        gas-ccgt-ccs: methane (incl. biofuels)
        gas-ocgt: methane (incl. biofuels)
        gas-ocgt-old: methane (incl. biofuels)
        gas-ocgt-new: methane (incl. biofuels)
        gas-conv: methane (incl. biofuels)
        gas-conv-old1: methane (incl. biofuels)
        gas-conv-old2: methane (incl. biofuels)
        battery discharger: battery
        urban central solid biomass CHP: chp and small thermal
        PHS: hydro and pumped storage
        hydro: hydro and pumped storage
        ror: hydro and pumped storage
        hydro-phs-turbine: hydro and pumped storage
        hydro-phs-pure-turbine: hydro and pumped storage
        hydro-ror: hydro and pumped storage
        hydro-pondage: hydro and pumped storage
        hydro-reservoir: hydro and pumped storage
        other-res-biomass: small scale res
        other-res-mix: small scale res
        other-non-res-gas-conv: chp and small thermal
        other-non-res-gas-conv-old1: chp and small thermal
        other-non-res-gas-conv-old2: chp and small thermal
        other-non-res-gas-ccgt: chp and small thermal
        other-non-res-gas-ccgt-old1: chp and small thermal
        other-non-res-gas-ccgt-old2: chp and small thermal
        other-non-res-gas-ccgt-new: chp and small thermal
        other-non-res-gas-ccgt-present1: chp and small thermal
        other-non-res-gas-ccgt-present2: chp and small thermal
        other-non-res-gas-ccgt-ccs: chp and small thermal
        other-non-res-gas-ocgt: chp and small thermal
        other-non-res-gas-ocgt-old: chp and small thermal
        other-non-res-gas-ocgt-new: chp and small thermal
        other-non-res-coal: chp and small thermal
        other-non-res-coal-old1: chp and small thermal
        other-non-res-coal-old2: chp and small thermal
        other-non-res-coal-new: chp and small thermal
        other-non-res-coal-ccs: chp and small thermal
        other-non-res-lignite: chp and small thermal
        other-non-res-lignite-old1: chp and small thermal
        other-non-res-lignite-old2: chp and small thermal
        other-non-res-lignite-new: chp and small thermal
        other-non-res-lignite-ccs: chp and small thermal
        other-non-res-oil-light: chp and small thermal
        other-non-res-oil-heavy: chp and small thermal
        other-non-res-oil-heavy-old1: chp and small thermal
        other-non-res-oil-heavy-old2: chp and small thermal
        other-non-res-oil-shale: chp and small thermal
        other-non-res-oil-shale-old: chp and small thermal
        other-non-res-oil-shale-new: chp and small thermal
        OCGT: slack generator

    power_generation:
      table_type: scenario_comparison
      rfc_sources:
      - market_out
      - report
      unit: TWh
      report:
        sheet_name: 26-
        index_col: [2, 3]
        header: 4
        nrows: 10
        ncolumns: 16
        names:
          index:
          - scenario
          - year
          column:
          - carrier
      mapping:
        offwind-dc-fl-r: wind offshore
        offwind-dc-fl-oh: wind offshore
        offwind-dc-fb-r: wind offshore
        offwind-dc-fb-oh: wind offshore
        offwind-ac-fl-r: wind offshore
        offwind-ac-fb-r: wind offshore
        offwind-h2-fb-oh: wind offshore
        offwind-h2-fl-oh: wind offshore
        onwind: wind onshore
        solar-pv-rooftop: solar
        solar-pv-utility: solar
        h2-ccgt: hydrogen
        h2-fuel-cell: hydrogen
        coal: coal + other fossil (incl. biofuels)
        coal-old1: coal + other fossil (incl. biofuels)
        coal-old2: coal + other fossil (incl. biofuels)
        coal-new: coal + other fossil (incl. biofuels)
        coal+ccs: coal + other fossil (incl. biofuels)
        lignite: coal + other fossil (incl. biofuels)
        lignite-old1: coal + other fossil (incl. biofuels)
        lignite-old2: coal + other fossil (incl. biofuels)
        lignite-new: coal + other fossil (incl. biofuels)
        lignite+ccs: coal + other fossil (incl. biofuels)
        oil-heavy: oil (incl. biofuels)
        oil-heavy-old1: oil (incl. biofuels)
        oil-heavy-old2: oil (incl. biofuels)
        oil-light: oil (incl. biofuels)
        oil-shale: oil (incl. biofuels)
        oil-shale-old: oil (incl. biofuels)
        oil-shale-new: oil (incl. biofuels)
        gas-ccgt: methane (incl. biofuels)
        gas-ccgt-old1: methane (incl. biofuels)
        gas-ccgt-old2: methane (incl. biofuels)
        gas-ccgt-new: methane (incl. biofuels)
        gas-ccgt-present1: methane (incl. biofuels)
        gas-ccgt-present2: methane (incl. biofuels)
        gas-ccgt-ccs: methane (incl. biofuels)
        gas-ocgt: methane (incl. biofuels)
        gas-ocgt-old: methane (incl. biofuels)
        gas-ocgt-new: methane (incl. biofuels)
        gas-conv: methane (incl. biofuels)
        gas-conv-old1: methane (incl. biofuels)
        gas-conv-old2: methane (incl. biofuels)
        urban central solid biomass CHP: other non-res
        ror: hydro (exc. pump storage)
        hydro: hydro (exc. pump storage)
        hydro-ror: hydro (exc. pump storage)
        hydro-pondage: hydro (exc. pump storage)
        hydro-reservoir: hydro (exc. pump storage)
        other-res-biomass: other res
        other-res-mix: other res
        other-non-res-gas-conv: other non-res
        other-non-res-gas-conv-old1: other non-res
        other-non-res-gas-conv-old2: other non-res
        other-non-res-gas-ccgt: other non-res
        other-non-res-gas-ccgt-old1: other non-res
        other-non-res-gas-ccgt-old2: other non-res
        other-non-res-gas-ccgt-new: other non-res
        other-non-res-gas-ccgt-present1: other non-res
        other-non-res-gas-ccgt-present2: other non-res
        other-non-res-gas-ccgt-ccs: other non-res
        other-non-res-gas-ocgt: other non-res
        other-non-res-gas-ocgt-old: other non-res
        other-non-res-gas-ocgt-new: other non-res
        other-non-res-coal: other non-res
        other-non-res-coal-old1: other non-res
        other-non-res-coal-old2: other non-res
        other-non-res-coal-new: other non-res
        other-non-res-coal-ccs: other non-res
        other-non-res-lignite: other non-res
        other-non-res-lignite-old1: other non-res
        other-non-res-lignite-old2: other non-res
        other-non-res-lignite-new: other non-res
        other-non-res-lignite-ccs: other non-res
        other-non-res-oil-light: other non-res
        other-non-res-oil-heavy: other non-res
        other-non-res-oil-heavy-old1: other non-res
        other-non-res-oil-heavy-old2: other non-res
        other-non-res-oil-shale: other non-res
        other-non-res-oil-shale-old: other non-res
        other-non-res-oil-shale-new: other non-res
        load: demand shedding
        OCGT: slack generator

    methane_supply:
      table_type: scenario_comparison
      rfc_sources:
      - report
      unit: TWh
      report:
        sheet_name: 32-
        index_col: 2
        header: [6, 7]
        nrows: 13
        ncolumns: 9
        names:
          index:
          - carrier
          column:
          - scenario
          - year
      mapping:
        Sabatier: synthetic methane (domestic)
        biogas to gas: biomethane (domestic)
        gas: natural gas (import)

    hydrogen_supply:
      table_type: scenario_comparison
      rfc_sources:
      - market_out
      - report
      unit: TWh
      report:
        sheet_name: 33-
        index_col: 2
        header: [4, 5]
        nrows: 13
        ncolumns: 9
        names:
          index:
          - carrier
          column:
          - scenario
          - year
      mapping:
        H2 Electrolysis: p2g
        H2 import LH2: ammonia imports
        H2 import Pipeline: imports (renewable & low carbon)
        SMR: smr (grey) and smr with ccs (blue)
        SMR CC: smr (grey) and smr with ccs (blue)
        load: demand shedding

    biomass_supply:
      table_type: scenario_comparison
      rfc_sources:
      - report
      unit: TWh
      report:
        sheet_name: 22-
        index_col: 2
        header: [3, 4]
        names:
          index:
          - carrier
          column:
          - scenario
          - year
      mapping:
        biomass final energy demand: final demand
        biomass to liquid: for biofuels
        biomass to liquid CC: for biofuels
        biogas: for biomethane
        other-res-biomass: other res
      biomass_to_methane_efficiency:
        # Values from TYNDP 2024 Supply Tool
        2030: 0.68
        2035: 0.68  # Interpolated
        2040: 0.68
        2045: 0.68  # Interpolated
        2050: 0.68
      biogas_not_upgraded:
        # Values from TYNDP 2024 Supply Tool, EU27, 8760h
        2030: 33  # TWh
        2035: 45
        2040: 56

    energy_imports:
      table_type: scenario_comparison
      rfc_sources:
      - report
      unit: TWh
      report:
        sheet_name: 60-
        index_col: 2
        header: [3, 4]
        names:
          index:
          - carrier
          column:
          - scenario
          - year
      mapping:
        H2 import LH2: hydrogen
        H2 import Pipeline: hydrogen
        coal: solids
        lignite: solids
        oil primary: liquids
        gas: methane

    generation_profiles:
      table_type: time_series
      rfc_sources:
      - report
      unit: GW
      report:
        sheet_name:
          DE: 30a
          GA: 30b
        index_col: 1
        header: 4
        names:
          index:
          - snapshot
          column:
          - carrier
      mapping:
        offwind-dc-fl-r: offshore wind
        offwind-dc-fl-oh: offshore wind
        offwind-dc-fb-r: offshore wind
        offwind-dc-fb-oh: offshore wind
        offwind-ac-fl-r: offshore wind
        offwind-ac-fb-r: offshore wind
        onwind: onshore wind
        solar-pv-rooftop: solar
        solar-pv-utility: solar
        h2-ccgt: methane&hydrogen
        h2-fuel-cell: methane&hydrogen
        gas-ccgt: methane&hydrogen
        gas-ccgt-old1: methane&hydrogen
        gas-ccgt-old2: methane&hydrogen
        gas-ccgt-new: methane&hydrogen
        gas-ccgt-present1: methane&hydrogen
        gas-ccgt-present2: methane&hydrogen
        gas-ccgt-ccs: methane&hydrogen
        gas-ocgt: methane&hydrogen
        gas-ocgt-old: methane&hydrogen
        gas-ocgt-new: methane&hydrogen
        gas-conv: methane&hydrogen
        gas-conv-old1: methane&hydrogen
        gas-conv-old2: methane&hydrogen
        coal: coal&lignite&oil
        coal-old1: coal&lignite&oil
        coal-old2: coal&lignite&oil
        coal-new: coal&lignite&oil
        coal+ccs: coal&lignite&oil
        lignite: coal&lignite&oil
        lignite-old1: coal&lignite&oil
        lignite-old2: coal&lignite&oil
        lignite-new: coal&lignite&oil
        lignite+ccs: coal&lignite&oil
        oil: coal&lignite&oil
        oil-heavy: coal&lignite&oil
        oil-heavy-old1: coal&lignite&oil
        oil-heavy-old2: coal&lignite&oil
        oil-light: coal&lignite&oil
        oil-shale: coal&lignite&oil
        oil-shale-old: coal&lignite&oil
        oil-shale-new: coal&lignite&oil
        battery discharger: battery
        urban central solid biomass CHP: other res
        PHS: hydro
        ror: hydro
        hydro: hydro
        hydro-phs-turbine: hydro
        hydro-phs-pure-turbine: hydro
        hydro-ror: hydro
        hydro-pondage: hydro
        hydro-reservoir: hydro
        other-res-biomass: other res
        other-res-mix: other res
        other-non-res-gas-conv: other non-res
        other-non-res-gas-conv-old1: other non-res
        other-non-res-gas-conv-old2: other non-res
        other-non-res-gas-ccgt: other non-res
        other-non-res-gas-ccgt-old1: other non-res
        other-non-res-gas-ccgt-old2: other non-res
        other-non-res-gas-ccgt-new: other non-res
        other-non-res-gas-ccgt-present1: other non-res
        other-non-res-gas-ccgt-present2: other non-res
        other-non-res-gas-ccgt-ccs: other non-res
        other-non-res-gas-ocgt: other non-res
        other-non-res-gas-ocgt-old: other non-res
        other-non-res-gas-ocgt-new: other non-res
        other-non-res-coal: other non-res
        other-non-res-coal-old1: other non-res
        other-non-res-coal-old2: other non-res
        other-non-res-coal-new: other non-res
        other-non-res-coal-ccs: other non-res
        other-non-res-lignite: other non-res
        other-non-res-lignite-old1: other non-res
        other-non-res-lignite-old2: other non-res
        other-non-res-lignite-new: other non-res
        other-non-res-lignite-ccs: other non-res
        other-non-res-oil-light: other non-res
        other-non-res-oil-heavy: other non-res
        other-non-res-oil-heavy-old1: other non-res
        other-non-res-oil-heavy-old2: other non-res
        other-non-res-oil-shale: other non-res
        other-non-res-oil-shale-old: other non-res
        other-non-res-oil-shale-new: other non-res

    electricity_price:
      table_type: prices
      rfc_sources:
      - market_out
      unit: EUR/MWh_e

    electricity_price_excl_shed:
      table_type: prices
      rfc_sources:
      - market_out
      unit: EUR/MWh_e

    hydrogen_price:
      table_type: prices
      rfc_sources:
      - market_out
      unit: EUR/MWh_H2

    hydrogen_price_excl_shed:
      table_type: prices
      rfc_sources:
      - market_out
      unit: EUR/MWh_H2

    crossborder_electricity:
      table_type: flows
      rfc_sources:
      - market_out
      unit: MWh

    crossborder_hydrogen:
      table_type: flows
      rfc_sources:
      - market_out
      unit: MWh
