# SPDX-FileCopyrightText: Contributors to Open-TYNDP <https://github.com/open-energy-transition/open-tyndp>
#
# SPDX-License-Identifier: CC0-1.0

benchmarking:
  enable: false
  remove_last_day: false
  spatial:
    by_bus: true
    by_country: true


  tables:
    power_capacity:
      table_type: scenario_comparison
      mapping_col: benchmarking_capacity
      rfc_sources:
      - market_out
      - report
      - vp
      unit: GW
      report:
        sheet_name: 25-
        index_col: [2, 3]
        header: 4
        nrows: 10
        ncolumns: 17
        names:
          index:
          - scenario
          - year
          column:
          - carrier

    power_generation:
      table_type: scenario_comparison
      mapping_col: benchmarking_generation
      rfc_sources:
      - market_out
      - report
      unit: TWh
      report:
        sheet_name: 26-
        index_col: [2, 3]
        header: 4
        nrows: 10
        ncolumns: 16
        names:
          index:
          - scenario
          - year
          column:
          - carrier

    final_energy_demand:
      table_type: scenario_comparison
      mapping_col: benchmarking_fed
      rfc_sources:
      - report
      unit: TWh
      report:
        sheet_name: 5-
        index_col: 2
        header: [4, 5]
        names:
          index:
          - carrier
          column:
          - scenario
          - year

    electricity_demand:
      table_type: scenario_comparison
      mapping_col: benchmarking_elec_demand
      rfc_sources:
      - market_out
      - report
      - vp
      unit: TWh
      report:
        sheet_name: 23-
        index_col: [2, 3]
        header: 4
        names:
          index:
          - scenario
          - year
          column:
          - carrier

    methane_demand:
      table_type: scenario_comparison
      mapping_col: benchmarking_ch4_demand
      rfc_sources:
      - report
      unit: TWh
      report:
        sheet_name: 8-
        index_col: 2
        header: [4, 5]
        nrows: 15
        names:
          index:
          - carrier
          column:
          - scenario
          - year

    hydrogen_demand:
      table_type: scenario_comparison
      mapping_col: benchmarking_h2_demand
      rfc_sources:
      - market_out
      - report
      unit: TWh
      report:
        sheet_name: 10-
        index_col: 2
        header: [4, 5]
        nrows: 15
        names:
          index:
          - carrier
          column:
          - scenario
          - year

    methane_supply:
      table_type: scenario_comparison
      mapping_col: benchmarking_ch4_supply
      rfc_sources:
      - report
      unit: TWh
      report:
        sheet_name: 32-
        index_col: 2
        header: [6, 7]
        nrows: 13
        ncolumns: 9
        names:
          index:
          - carrier
          column:
          - scenario
          - year

    hydrogen_supply:
      table_type: scenario_comparison
      mapping_col: benchmarking_h2_supply
      rfc_sources:
      - market_out
      - report
      unit: TWh
      report:
        sheet_name: 33-
        index_col: 2
        header: [4, 5]
        nrows: 13
        ncolumns: 9
        names:
          index:
          - carrier
          column:
          - scenario
          - year

    biomass_supply:
      table_type: scenario_comparison
      mapping_col: benchmarking_biomass_supply
      rfc_sources:
      - report
      unit: TWh
      report:
        sheet_name: 22-
        index_col: 2
        header: [3, 4]
        names:
          index:
          - carrier
          column:
          - scenario
          - year
      biomass_to_methane_efficiency:
        # Values from TYNDP 2024 Supply Tool
        2030: 0.68
        2035: 0.68  # Interpolated
        2040: 0.68
        2045: 0.68  # Interpolated
        2050: 0.68
      biogas_not_upgraded:
        # Values from TYNDP 2024 Supply Tool, EU27, 8760h
        2030: 33  # TWh
        2035: 45
        2040: 56

    energy_imports:
      table_type: scenario_comparison
      mapping_col: benchmarking_energy_imports
      rfc_sources:
      - report
      unit: TWh
      report:
        sheet_name: 60-
        index_col: 2
        header: [3, 4]
        names:
          index:
          - carrier
          column:
          - scenario
          - year

    generation_profiles:
      table_type: time_series
      mapping_col: benchmarking_generation_profiles
      rfc_sources:
      - report
      unit: GW
      report:
        sheet_name:
          DE: 30a
          GA: 30b
        index_col: 1
        header: 4
        names:
          index:
          - snapshot
          column:
          - carrier

    electricity_price:
      table_type: prices
      mapping_col: benchmarking_prices
      rfc_sources:
      - market_out
      unit: EUR/MWh_e

    electricity_price_excl_shed:
      table_type: prices
      mapping_col: benchmarking_prices
      rfc_sources:
      - market_out
      unit: EUR/MWh_e
      exclude_coupling_effects: true  # If true, derive threshold from VOLL EUR/MWh_H2 × electrolysis efficiency

    hydrogen_price:
      table_type: prices
      mapping_col: benchmarking_prices
      rfc_sources:
      - market_out
      unit: EUR/MWh_H2

    hydrogen_price_excl_shed:
      table_type: prices
      mapping_col: benchmarking_prices
      rfc_sources:
      - market_out
      unit: EUR/MWh_H2
      exclude_coupling_effects: true  # If true, derive threshold from VOLL EUR/MWh_e × H2-CCGT efficiency

    crossborder_electricity:
      table_type: flows
      rfc_sources:
      - market_out
      unit: MWh

    crossborder_hydrogen:
      table_type: flows
      rfc_sources:
      - market_out
      unit: MWh

    electricity_demand_shedding_hours:
      table_type: hours
      mapping_col: benchmarking_shed_hours
      rfc_sources:
      - market_out
      unit: hours

    hydrogen_demand_shedding_hours:
      table_type: hours
      mapping_col: benchmarking_shed_hours
      rfc_sources:
      - market_out
      unit: hours
